// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJCPVMhHMu2lH-IPBBzWFSmKnD-oWrDDU',
    appId: '1:804339776474:web:8ef2a60d1defbcd2b71ee3',
    messagingSenderId: '804339776474',
    projectId: 'ivet-technomart',
    authDomain: 'ivet-technomart.firebaseapp.com',
    storageBucket: 'ivet-technomart.firebasestorage.app',
    measurementId: 'G-11YPJBJY5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2ihu0v541-I_kfEWxXye69kDT6Zq0O6A',
    appId: '1:804339776474:android:00692e5a05358b0db71ee3',
    messagingSenderId: '804339776474',
    projectId: 'ivet-technomart',
    storageBucket: 'ivet-technomart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSrRk0jQVJvy9SHI9Fe8ES5-SuOeGMiHc',
    appId: '1:804339776474:ios:59212709b7eb5d78b71ee3',
    messagingSenderId: '804339776474',
    projectId: 'ivet-technomart',
    storageBucket: 'ivet-technomart.firebasestorage.app',
    iosBundleId: 'com.codingwitht.ecommerce.tstoreEcommerceApp',
  );
}
